/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedConsultorRouteImport } from './routes/_authenticated/consultor'
import { Route as AuthenticatedConsultorRiscosRouteImport } from './routes/_authenticated/consultor-riscos'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEntidadesRouteImport } from './routes/_authenticated/entidades'
import { Route as AuthenticatedFamiliaRouteImport } from './routes/_authenticated/familia'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedProjecaoRouteImport } from './routes/_authenticated/projecao'
import { Route as AuthenticatedRecorrenciasRouteImport } from './routes/_authenticated/recorrencias'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ApiFinanceAdvisorRouteImport } from './routes/api.finance.advisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultorRoute = AuthenticatedConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultorRiscosRoute =
  AuthenticatedConsultorRiscosRouteImport.update({
    id: '/consultor-riscos',
    path: '/consultor-riscos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntidadesRoute = AuthenticatedEntidadesRouteImport.update({
  id: '/entidades',
  path: '/entidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliaRoute = AuthenticatedFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjecaoRoute = AuthenticatedProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecorrenciasRoute =
  AuthenticatedRecorrenciasRouteImport.update({
    id: '/recorrencias',
    path: '/recorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceAdvisorRoute = ApiFinanceAdvisorRouteImport.update({
  id: '/api/finance/advisor',
  path: '/api/finance/advisor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/consultor-riscos': typeof AuthenticatedConsultorRiscosRoute
  '/contas': typeof AuthenticatedContasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/entidades': typeof AuthenticatedEntidadesRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/recorrencias': typeof AuthenticatedRecorrenciasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/finance/advisor': typeof ApiFinanceAdvisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/consultor-riscos': typeof AuthenticatedConsultorRiscosRoute
  '/contas': typeof AuthenticatedContasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/entidades': typeof AuthenticatedEntidadesRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/recorrencias': typeof AuthenticatedRecorrenciasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/finance/advisor': typeof ApiFinanceAdvisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/consultor': typeof AuthenticatedConsultorRoute
  '/_authenticated/consultor-riscos': typeof AuthenticatedConsultorRiscosRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/entidades': typeof AuthenticatedEntidadesRoute
  '/_authenticated/familia': typeof AuthenticatedFamiliaRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/projecao': typeof AuthenticatedProjecaoRoute
  '/_authenticated/recorrencias': typeof AuthenticatedRecorrenciasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/finance/advisor': typeof ApiFinanceAdvisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cartoes'
    | '/categorias'
    | '/consultor'
    | '/consultor-riscos'
    | '/contas'
    | '/dashboard'
    | '/documentos'
    | '/entidades'
    | '/familia'
    | '/lancamentos'
    | '/orcamento'
    | '/pendencias'
    | '/projecao'
    | '/recorrencias'
    | '/relatorios'
    | '/reservas'
    | '/revisar'
    | '/whatsapp'
    | '/convite/$token'
    | '/api/finance/advisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cartoes'
    | '/categorias'
    | '/consultor'
    | '/consultor-riscos'
    | '/contas'
    | '/dashboard'
    | '/documentos'
    | '/entidades'
    | '/familia'
    | '/lancamentos'
    | '/orcamento'
    | '/pendencias'
    | '/projecao'
    | '/recorrencias'
    | '/relatorios'
    | '/reservas'
    | '/revisar'
    | '/whatsapp'
    | '/convite/$token'
    | '/api/finance/advisor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cartoes'
    | '/_authenticated/categorias'
    | '/_authenticated/consultor'
    | '/_authenticated/consultor-riscos'
    | '/_authenticated/contas'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/entidades'
    | '/_authenticated/familia'
    | '/_authenticated/lancamentos'
    | '/_authenticated/orcamento'
    | '/_authenticated/pendencias'
    | '/_authenticated/projecao'
    | '/_authenticated/recorrencias'
    | '/_authenticated/relatorios'
    | '/_authenticated/reservas'
    | '/_authenticated/revisar'
    | '/_authenticated/whatsapp'
    | '/convite/$token'
    | '/api/finance/advisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiFinanceAdvisorRoute: typeof ApiFinanceAdvisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultor': {
      id: '/_authenticated/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof AuthenticatedConsultorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultor-riscos': {
      id: '/_authenticated/consultor-riscos'
      path: '/consultor-riscos'
      fullPath: '/consultor-riscos'
      preLoaderRoute: typeof AuthenticatedConsultorRiscosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entidades': {
      id: '/_authenticated/entidades'
      path: '/entidades'
      fullPath: '/entidades'
      preLoaderRoute: typeof AuthenticatedEntidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familia': {
      id: '/_authenticated/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof AuthenticatedFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projecao': {
      id: '/_authenticated/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof AuthenticatedProjecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorrencias': {
      id: '/_authenticated/recorrencias'
      path: '/recorrencias'
      fullPath: '/recorrencias'
      preLoaderRoute: typeof AuthenticatedRecorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/advisor': {
      id: '/api/finance/advisor'
      path: '/api/finance/advisor'
      fullPath: '/api/finance/advisor'
      preLoaderRoute: typeof ApiFinanceAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedConsultorRoute: typeof AuthenticatedConsultorRoute
  AuthenticatedConsultorRiscosRoute: typeof AuthenticatedConsultorRiscosRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEntidadesRoute: typeof AuthenticatedEntidadesRoute
  AuthenticatedFamiliaRoute: typeof AuthenticatedFamiliaRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedProjecaoRoute: typeof AuthenticatedProjecaoRoute
  AuthenticatedRecorrenciasRoute: typeof AuthenticatedRecorrenciasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartoesRoute: AuthenticatedCartoesRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedConsultorRoute: AuthenticatedConsultorRoute,
  AuthenticatedConsultorRiscosRoute: AuthenticatedConsultorRiscosRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEntidadesRoute: AuthenticatedEntidadesRoute,
  AuthenticatedFamiliaRoute: AuthenticatedFamiliaRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedProjecaoRoute: AuthenticatedProjecaoRoute,
  AuthenticatedRecorrenciasRoute: AuthenticatedRecorrenciasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiFinanceAdvisorRoute: ApiFinanceAdvisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
